# Generated by Django 4.2.3 on 2023-08-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("pic", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="CarFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Engine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="None Selected", max_length=50, null=True),
                ),
                ("engCapacity", models.IntegerField(null=True)),
                ("engNum", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Showroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("telephone", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("role", models.CharField(max_length=50)),
                ("staff_pic", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "showroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showroom",
                        to="showroom.showroom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True)),
                ("pic", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "carBrand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbrand",
                        to="showroom.carbrand",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                ("name", models.CharField(default="Unnamed", max_length=50)),
                ("year", models.IntegerField(null=True)),
                ("price", models.IntegerField(null=True)),
                ("mileage", models.IntegerField(null=True)),
                ("pic", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "chassis_num",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "carModel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carmodels",
                        to="showroom.carmodel",
                    ),
                ),
                (
                    "engine",
                    models.OneToOneField(
                        default="None",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engine",
                        to="showroom.engine",
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        related_name="features", to="showroom.carfeature"
                    ),
                ),
            ],
        ),
    ]
