# Generated by Django 4.2.3 on 2023-07-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0003_carbrand_carmodel_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carbrand",
                to="showroom.carbrand",
            ),
        ),
    ]
