# Generated by Django 4.2.3 on 2023-07-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0004_alter_carmodel_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carmodel",
            old_name="brand",
            new_name="carBrand",
        ),
    ]
