# Generated by Django 4.2.3 on 2023-08-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0005_rename_brand_carmodel_carbrand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="model",
            new_name="carModel",
        ),
    ]
