# Generated by Django 4.2.3 on 2023-08-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0007_car_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="id",
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.OneToOneField(
                default=99999,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="engine",
                serialize=False,
                to="showroom.engine",
            ),
            preserve_default=False,
        ),
    ]
