# Generated by Django 4.2.3 on 2023-08-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0009_alter_engine_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="chassis_num",
            field=models.CharField(
                default="-1", max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engine",
                to="showroom.engine",
            ),
        ),
    ]
